dist: trusty
sudo: false

stages:
  - test
  - name: deploy
    if: (branch = master) AND tag IS blank AND type != pull_request

jobs:
  include:
    - language: node_js
      node_js:
        - '13'
      addons:
        chrome: stable
      script: make test-fe
    - language: java
      before-script: cd apsi-enrollment-be
      script: "./gradlew build"
    - stage: deploy
      addons:
        ssh_known_hosts:
        - 51.178.84.158
      script: echo "Deploying..."
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
      deploy:
        provider: script
        script: ssh -i /tmp/deploy_rsa apsi@51.178.84.158 ./deploy.sh
        on:
          all-branches: true
