version: '2.0'
services:
  web:
    build: apsi-enrollment-fe/.
    ports:
      - "80:80"
    depends_on:
      - rest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  rest:
    build: apsi-enrollment-be/.
